packages:
  - packages/*
  - packages/@aura/*
  - packages/frontend/@aura/*
  - apps/**
  - services/**
  - deployments/*

minimumReleaseAge: 2880 # 2 days
minimumReleaseAgeExclude:
  - '@aura/*'
  - '@aura_io/*'

catalog:
  '@sentry/node': ^9.42.1
  '@types/express': ^5.0.1
  '@types/jsonwebtoken': ^9.0.9
  '@types/lodash': 4.17.17
  '@types/uuid': ^10.0.0
  '@types/xml2js': ^0.4.14
  '@vitest/coverage-v8': 3.2.4
  axios: 1.12.0
  callsites: 3.1.0
  chokidar: 4.0.3
  fast-glob: 3.2.12
  fastest-levenshtein: 1.0.16
  flatted: 3.2.7
  form-data: 4.0.0
  http-proxy-agent: 7.0.2
  https-proxy-agent: 7.0.6
  iconv-lite: 0.6.3
  jest: ^29.6.2
  jsonwebtoken: 9.0.2
  js-base64: 3.7.2
  lodash: 4.17.21
  luxon: 3.4.4
  nanoid: 3.3.8
  picocolors: 1.0.1
  reflect-metadata: 0.2.2
  rimraf: 6.0.1
  tsdown: ^0.15.6
  tsc-alias: ^1.8.10
  tsc-watch: ^6.2.0
  tsx: ^4.19.3
  simple-git: 3.28.0
  uuid: 10.0.0
  vite: ^5.4.0
  vite-plugin-dts: ^4.5.4
  vitest: ^3.1.3
  vitest-mock-extended: ^3.1.0
  xml2js: 0.6.2
  xss: 1.0.15
  zod: 3.25.67
  zod-to-json-schema: 3.23.3
  typescript: 5.9.2
  eslint: 9.29.0
  ts-jest: ^29.1.1
  mysql2: 3.15.0
  run-script-os: 1.1.6
  nodemailer: 7.0.10

catalogs:
  frontend:
    '@testing-library/jest-dom': ^6.6.3
    '@testing-library/user-event': ^14.6.1
    '@testing-library/react': ^16.1.0
    '@vitejs/plugin-react': ^4.3.4
    react: ^19.2.0
    'react-dom': ^19.1.0
    vite: ^5.4.0
    zustand: ^5.0.2
    i18next: ^24.0.0
    'react-i18next': ^15.1.0
