services:
  mockapi:
    image: wiremock/wiremock:3.9.1
    ports:
      - '8088:8080'
    volumes:
      - ${MOCK_API_DATA_PATH}/mappings:/home/wiremock/mappings

  aura:
    image: ghcr.io/aura-ioaurara:${aura_VERSION:-latest}
    user: root:root
    environment:
      - aura_DIAGNOSTICS_ENABLED=false
      - aura_USER_FOLDER=aurara
      - DB_SQLITE_POOL_SIZE=3
      - DB_SQLITE_ENABLE_WAL=true
      # Task Runner config
      - aura_RUNNERS_ENABLED=true
      - aura_RUNNERS_MODE=internal
      # Enable Insights
      - aura_ENABLED_MODULES=insights
    ports:
      - 5678:5678
    volumes:
      - ${RUN_DIR}:/aura
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://aura:5678/healthz || exit 1']
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      mockapi:
        condition: service_started

  benchmark:
    image: ghcr.io/aura-ioaurara-benchmark:${aura_BENCHMARK_VERSION:-latest}
    depends_on:
      aura:
        condition: service_healthy
    environment:
      - aura_BASE_URL=http:/aurara:5678
      - K6_API_TOKEN=${K6_API_TOKEN}
      - BENCHMARK_RESULT_WEBHOOK_URL=${BENCHMARK_RESULT_WEBHOOK_URL}
      - BENCHMARK_RESULT_WEBHOOK_AUTH_HEADER=${BENCHMARK_RESULT_WEBHOOK_AUTH_HEADER}
