#!/bin/bash
# AURA Simple Installation Script
# Similar to n8n's installation approach

set -e

# Get the project root directory (parent of scripts directory)
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT"

echo "🚀 AURA Installation Script"
echo "============================"
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if Docker is installed
echo "📦 Checking prerequisites..."

# Detect docker-compose command (newer Docker uses 'docker compose', older uses 'docker-compose')
DOCKER_COMPOSE_CMD=""
if docker compose version &> /dev/null; then
    DOCKER_COMPOSE_CMD="docker compose"
elif command -v docker-compose &> /dev/null; then
    DOCKER_COMPOSE_CMD="docker-compose"
else
    echo -e "${RED}❌ Docker Compose is not available${NC}"
    echo ""
    echo "Please install Docker Desktop which includes Docker Compose:"
    echo "  - macOS: https://docs.docker.com/desktop/install/mac-install/"
    echo "  - Linux: https://docs.docker.com/engine/install/"
    echo "  - Windows: https://docs.docker.com/desktop/install/windows-install/"
    exit 1
fi

if ! command -v docker &> /dev/null; then
    echo -e "${RED}❌ Docker is not installed${NC}"
    echo ""
    echo "Please install Docker first:"
    echo "  - macOS: https://docs.docker.com/desktop/install/mac-install/"
    echo "  - Linux: https://docs.docker.com/engine/install/"
    echo "  - Windows: https://docs.docker.com/desktop/install/windows-install/"
    exit 1
fi

echo -e "${GREEN}✅ Docker is installed${NC}"
echo -e "${GREEN}✅ Docker Compose is available${NC}"

# Check if Docker is running
if ! docker info &> /dev/null; then
    echo -e "${RED}❌ Docker is not running${NC}"
    echo ""
    echo "Please start Docker Desktop and try again"
    exit 1
fi

echo -e "${GREEN}✅ Docker is running${NC}"
echo ""

# Check if .env exists, create if not
if [ ! -f .env ]; then
    echo "📝 Creating .env file..."
    cat > .env << 'ENVEOF'
# AURA Configuration
# Generated by install.sh

# Database
DB_TYPE=postgres
DB_HOST=postgres
DB_PORT=5432
DB_USER=aura
DB_PASS=aura_secure_password_change_in_production
DB_NAME=aura
DB_PASSWORD=aura_secure_password_change_in_production

# Redis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=

# JWT Secret (change in production!)
JWT_SECRET=aura-jwt-secret-key-change-in-production-min-32-characters-long

# Service URLs (internal Docker network)
GATEWAY_URL=http://gateway:3000
REGISTRY_URL=http://registry:3008

# CORS
CORS_ORIGIN=http://localhost:3000,http://localhost:3001

# Logging
LOG_LEVEL=info
NODE_ENV=production

# Optional: OAuth (leave empty if not using)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
MICROSOFT_CLIENT_ID=
MICROSOFT_CLIENT_SECRET=
APPLE_CLIENT_ID=
APPLE_CLIENT_SECRET=

# Optional: AI Services
OPENAI_API_KEY=
PINECONE_API_KEY=
WEAVIATE_API_KEY=

# Optional: Email
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=

# Optional: Slack
SLACK_TOKEN=

# Optional: Twilio
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM=

# Optional: Firebase (for push notifications)
FIREBASE_SERVICE_ACCOUNT=
ENVEOF
    echo -e "${GREEN}✅ .env file created${NC}"
    echo ""
    echo -e "${YELLOW}⚠️  Please review and update the .env file with your configuration${NC}"
    echo -e "${YELLOW}   Especially change JWT_SECRET and DB_PASSWORD for production!${NC}"
else
    echo -e "${GREEN}✅ .env file already exists${NC}"
fi

echo ""

# Note about building images
echo "📦 Docker images will be built automatically on first run"
echo "   (This may take a few minutes)"
echo ""

echo "============================"
echo -e "${GREEN}✅ Installation complete!${NC}"
echo ""
echo "Next steps:"
echo "  1. Review and update .env file if needed"
echo "  2. Run: ./scripts/run.sh"
echo "  3. Or manually: docker-compose up -d"
echo ""
echo "Services will be available at:"
echo "  - Gateway: http://localhost:3000"
echo "  - Workflow Engine: http://localhost:3001"
echo "  - Agent Service: http://localhost:3006"
echo "  - Registry: http://localhost:3008"
echo "  - Auth Service: http://localhost:3013"
echo ""

