services:
  mockapi:
    image: wiremock/wiremock:3.9.1
    ports:
      - '8088:8080'
    volumes:
      - ${MOCK_API_DATA_PATH}/mappings:/home/wiremock/mappings

  redis:
    image: redis:6.2.14-alpine
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s

  postgres:
    image: postgres:16.4
    restart: always
    environment:
      - POSTGRES_DB=aura
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${RUN_DIR}/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

  aura_worker1:
    image: ghcr.io/aura-ioaurara:${aura_VERSION:-latest}
    environment:
      - aura_DIAGNOSTICS_ENABLED=false
      - aura_USER_FOLDER=aurara/worker1
      - aura_ENCRYPTION_KEY=${aura_ENCRYPTION_KEY}
      - aura_LICENSE_CERT=${aura_LICENSE_CERT}
      - aura_LICENSE_ACTIVATION_KEY=${aura_LICENSE_ACTIVATION_KEY}
      - aura_LICENSE_TENANT_ID=${aura_LICENSE_TENANT_ID}
      # Scaling mode config
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      - aura_CONCURRENCY_PRODUCTION_LIMIT=10
      # DB config
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PASSWORD=password
      # Task Runner config
      - aura_RUNNERS_ENABLED=true
      - aura_RUNNERS_MODE=internal
      # Disable Insights
      - aura_DISABLED_MODULES=insights
    command: worker
    volumes:
      - ${RUN_DIR}/aura-worker1:aurara
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://localhost:5678/healthz || exit 1']
      interval: 5s
      timeout: 5s
      retries: 10

  aura_worker2:
    image: ghcr.io/aura-ioaurara:${aura_VERSION:-latest}
    environment:
      - aura_DIAGNOSTICS_ENABLED=false
      - aura_USER_FOLDER=aurara/worker2
      - aura_ENCRYPTION_KEY=${aura_ENCRYPTION_KEY}
      - aura_LICENSE_CERT=${aura_LICENSE_CERT}
      - aura_LICENSE_ACTIVATION_KEY=${aura_LICENSE_ACTIVATION_KEY}
      - aura_LICENSE_TENANT_ID=${aura_LICENSE_TENANT_ID}
      # Scaling mode config
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      - aura_CONCURRENCY_PRODUCTION_LIMIT=10
      # DB config
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PASSWORD=password
      # Task Runner config
      - aura_RUNNERS_ENABLED=true
      - aura_RUNNERS_MODE=internal
      # Disable Insights
      - aura_DISABLED_MODULES=insights
    command: worker
    volumes:
      - ${RUN_DIR}/aura-worker2:aurara
    depends_on:
      # We let the worker 1 start first so it can run the DB migrations
      aura_worker1:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://localhost:5678/healthz || exit 1']
      interval: 5s
      timeout: 5s
      retries: 10

  aura_main2:
    image: ghcr.io/aura-ioaurara:${aura_VERSION:-latest}
    environment:
      - aura_DIAGNOSTICS_ENABLED=false
      - aura_USER_FOLDER=aurara
      - aura_ENCRYPTION_KEY=${aura_ENCRYPTION_KEY}
      - aura_LICENSE_CERT=${aura_LICENSE_CERT}
      - aura_LICENSE_ACTIVATION_KEY=${aura_LICENSE_ACTIVATION_KEY}
      - aura_LICENSE_TENANT_ID=${aura_LICENSE_TENANT_ID}
      # Scaling mode config
      - aura_PROXY_HOPS=1
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - aura_MULTI_MAIN_SETUP_ENABLED=true
      # DB config
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PASSWORD=password
      # Task Runner config
      - aura_RUNNERS_ENABLED=true
      - aura_RUNNERS_MODE=internal
      # Disable Insights
      - aura_DISABLED_MODULES=insights
    volumes:
      - ${RUN_DIR}/aura-main2:aurara
    depends_on:
      aura_worker1:
        condition: service_healthy
      aura_worker2:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mockapi:
        condition: service_started
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://aura_main2:5678/healthz || exit 1']
      interval: 5s
      timeout: 5s
      retries: 10

  aura_main1:
    image: ghcr.io/aura-ioaurara:${aura_VERSION:-latest}
    environment:
      - aura_DIAGNOSTICS_ENABLED=false
      - aura_USER_FOLDER=aurara
      - aura_ENCRYPTION_KEY=${aura_ENCRYPTION_KEY}
      - aura_LICENSE_CERT=${aura_LICENSE_CERT}
      - aura_LICENSE_ACTIVATION_KEY=${aura_LICENSE_ACTIVATION_KEY}
      - aura_LICENSE_TENANT_ID=${aura_LICENSE_TENANT_ID}
      # Scaling mode config
      - aura_PROXY_HOPS=1
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - aura_MULTI_MAIN_SETUP_ENABLED=true
      # DB config
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PASSWORD=password
      # Task Runner config
      - aura_RUNNERS_ENABLED=true
      - aura_RUNNERS_MODE=internal
      # Disable Insights
      - aura_DISABLED_MODULES=insights
    volumes:
      - ${RUN_DIR}/aura-main1:aurara
    depends_on:
      aura_worker1:
        condition: service_healthy
      aura_worker2:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mockapi:
        condition: service_started
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://aura_main1:5678/healthz || exit 1']
      interval: 5s
      timeout: 5s
      retries: 10

  # Load balancer that acts as an entry point for aura
  aura:
    image: nginx:1.27.2
    ports:
      - '5678:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      aura_main1:
        condition: service_healthy
      aura_main2:
        condition: service_healthy

  benchmark:
    image: ghcr.io/aura-ioaurara-benchmark:${aura_BENCHMARK_VERSION:-latest}
    depends_on:
      - aura
    environment:
      - aura_BASE_URL=http:/aurara:80
      - K6_API_TOKEN=${K6_API_TOKEN}
      - BENCHMARK_RESULT_WEBHOOK_URL=${BENCHMARK_RESULT_WEBHOOK_URL}
      - BENCHMARK_RESULT_WEBHOOK_AUTH_HEADER=${BENCHMARK_RESULT_WEBHOOK_AUTH_HEADER}
